paths:
  static: ''
  uploads: uploads
timezone: Europe/London
markdown:
  engine: commonmark
  options: {}
collections_config:
  pages:
    path: ''
    glob:
      - index.html
    url: /
    icon: wysiwyg
  transformations:
    path: transformations
    glob:
      - index.html
    url: /transformations/
    icon: wysiwyg
